In [1]:
import numpy as np

In [2]:
ls = [3,6,9,"okk" , "done"]
ls

[3, 6, 9, 'okk', 'done']

In [3]:
ls * 2

[3, 6, 9, 'okk', 'done', 3, 6, 9, 'okk', 'done']

In [4]:
e = np.array([2,8,5,9])
e

array([2, 8, 5, 9])

In [5]:
t = np.array([4 , 8, 1, 9.4 ])
t

array([4. , 8. , 1. , 9.4])

In [6]:
m = np.array(["okk" , "done" , "verify"])
m

array(['okk', 'done', 'verify'], dtype='<U6')

In [9]:
e = np.array([2,8,5,9])
print("E :" , e)
print("TYPE:" , type(e))
print("DTYPE : " , e.dtype)

E : [2 8 5 9]
TYPE: <class 'numpy.ndarray'>
DTYPE :  int64

In [10]:
e2 = np.array([2 ,8 ,5.3 ,9 ])
print("E2 :" , e2)
print("TYPE e2:" , type(e2))
print("DTYPE : " , e2.dtype)

E2 : [2.  8.  5.3 9. ]
TYPE e2: <class 'numpy.ndarray'>
DTYPE :  float64

In [11]:
import pandas as pd

In [12]:
data = pd.read_csv("/content/Retail_Dataset_Modified.csv")
data

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [13]:
data.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring

In [14]:
data.head(3)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring

In [15]:
data.head(9)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
5,BX_DELHI_082,BrandX_India Superstore Delhi,BrandX_India,Street Store,Delhi,Metro,Toor Dal 1kg,Groceries,Dal,New Launch,...,81.3,85.3,Aggressive,Low,4.0,108,1,2022,Q1,Spring
6,BX_MUMBAI_062,BrandX_India Accessories Mumbai,BrandX_India,Street Store,Mumbai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Mature,...,98.0,81.6,Competitive,Low,2.0,90,1,2022,Q1,Spring
7,BX_DELHI_062,BrandX_India Digital Delhi,BrandX_India,Mall Store,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Mature,...,81.6,82.4,Competitive,Low,3.0,137,1,2022,Q1,Spring
8,BX_MUMBAI_042,BrandX_India Appliances Mumbai,BrandX_India,Street Store,Mumbai,Metro,NaN,Home Appliances,Water Purifiers,Declining,...,96.3,82.7,Aggressive,Low,4.0,214,1,2022,Q1,Spring

In [16]:
data.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [17]:
data.tail(7)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5164,BX_MUMBAI_020,BrandX_India Gadget Zone Mumbai,BrandX_India,Street Store,Mumbai,Metro,LG OLED 55Inch,Electronics,Smart TVs,Declining,...,79.6,88.4,Competitive,Low,1.0,101,8,2024,Q3,Monsoon
5165,BX_CHENNAI_047,BrandX_India Fresh Chennai,BrandX_India,Online Hub,Chennai,Metro,Moong Dal 1kg,Groceries,Dal,Mature,...,79.7,89.8,Aggressive,Low,2.0,99,1,2024,Q1,Spring
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [18]:
data.shape   # row  , columns

(5171, 47)

In [19]:
data.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [21]:
data.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   object
 1   Store_Name             5171 non-null   object
 2   Brand_Name             5171 non-null   object
 3   Store_Type             5171 non-null   object
 4   City                   5109 non-null   object
 5   City_Tier              5171 non-null   object
 6   Product_Name           5098 non-null   object
 7   Category               5171 non-null   object
 8   Sub_Category           5171 non-null   object
 9   Product_Stage          5171 non-null   object
 10  Quantity_Available     5171 non-null   object
 11  Units_Sold             5171 non-null   object
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   object
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   object
 20  Sales_Channel          5171 non-null   object
 21  Payment_Method         5171 non-null   object
 22  Supplier               5103 non-null   object
 23  Supplier_Rating        5171 non-null   object
 24  Promotion_Type         5171 non-null   object
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   object
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   object
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   object
 40  Weather_Impact         5171 non-null   object
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   object
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   object
 46  Season                 5171 non-null   object
dtypes: float64(11), int64(10), object(26)
memory usage: 1.9+ MB

In [23]:
dss = pd.read_csv("/content/titanic (1).csv")
dss

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [24]:
de = pd.read_excel("/content/Excel+LAB+7+Dataset_Dmart.xlsx")
de

,order_id,Order_Month,order_date,region,sales,category,discount,quantity,delivery_date,customer_type,payment_mode,profit,city,Unnamed: 13,Unnamed: 14
0,ORD100000,March,2023-03-30,East,713.49,Clothing,71.349,3,2023-04-01,Member,UPI,114.72,Pune,NaN,NaN
1,ORD100001,August,2023-08-28,West,3802.97,Electronics,380.297,4,2023-09-03,Regular,Card,971.41,Hyderabad,NaN,NaN
2,ORD100002,March,2024-03-09,North,3588.97,Home Care,358.897,7,2024-03-15,Regular,Cash,769.08,Bangalore,NaN,NaN
3,ORD100003,October,2024-10-13,East,1160.86,Electronics,116.086,5,2024-10-19,Member,UPI,71.61,Pune,NaN,NaN
4,ORD100004,April,2023-04-06,East,3071.32,Electronics,307.132,7,2023-04-09,New,Cash,621.92,Bangalore,Sales_By_North,Sales_By_East
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15340,ORD115340,November,2023-11-02,North,2910.33,Clothing,291.033,3,2023-11-03,New,Card,868.91,Pune,NaN,NaN
15341,ORD115341,July,2023-07-22,West,2723.39,Clothing,272.339,2,2023-07-25,New,Card,353.12,Pune,NaN,NaN
15342,ORD115342,June,2023-06-04,North,2400.38,Electronics,240.038,3,2023-06-06,Member,Card,231.20,Pune,NaN,NaN
15343,ORD115343,February,2024-02-20,East,2978.52,Personal Care,297.852,2,2024-02-27,Regular,Card,786.85,Hyderabad,NaN,NaN
15344,ORD115344,November,2023-11-18,South,4984.32,Grocery,498.432,3,2023-11-19,New,Card,909.10,Bangalore,NaN,NaN

In [25]:
idd = [123,456,789,2926]
name = ["Diva" , "Mahesh" , "Rakesh" , "Vikky"]
age = [20,25,18,10]

vb = pd.DataFrame({"IDD" : idd , "NAME" : name , "AGE" : age})
vb

    IDD    NAME  AGE
0   123    Diva   20
1   456  Mahesh   25
2   789  Rakesh   18
3  2926   Vikky   10

In [26]:
#idd = [123,456,789,2926]
name = ["Diva" , "Mahesh" , "Rakesh" , "Vikky"]
age = [20,25,18,10]

vb2 = pd.DataFrame({"NAME2" : name , "AGE2" : age})
vb2

    NAME2  AGE2
0    Diva    20
1  Mahesh    25
2  Rakesh    18
3   Vikky    10

In [27]:
type(vb2)

pandas.core.frame.DataFrame

In [28]:
idd = [123,456,789,2926]
name = ["Diva" , "Mahesh" , "Rakesh" , "Vikky"]
age = [20,25,18,10]

In [29]:
m = pd.Series(idd)
m

0     123
1     456
2     789
3    2926
dtype: int64

In [31]:
m3 = pd.Series(age,idd)
m3

123     20
456     25
789     18
2926    10
dtype: int64

In [32]:
m3.shape

(4,)

In [33]:
data.shape

(5171, 47)

In [34]:
vb

    IDD    NAME  AGE
0   123    Diva   20
1   456  Mahesh   25
2   789  Rakesh   18
3  2926   Vikky   10

In [36]:
vb.isnull()

     IDD   NAME    AGE
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [37]:
vb.isnull().sum()

IDD     0
NAME    0
AGE     0
dtype: int64

In [44]:
idd3 = [123,np.nan,2926]
name3 = ["Diva" , "Rakesh" , "Vikky"]
age3 = [20,25,18]

vb3 = pd.DataFrame({"IDD3" : idd3 , "NAME3" : name3 , "AGE3" : age3})
vb3

     IDD3   NAME3  AGE3
0   123.0    Diva    20
1     NaN  Rakesh    25
2  2926.0   Vikky    18

In [45]:
vb3.isnull()

    IDD3  NAME3   AGE3
0  False  False  False
1   True  False  False
2  False  False  False