In [28]:
import numpy as np
import pandas as pd

In [2]:
e = np.array([5,1,7,9,2])
e

array([5, 1, 7, 9, 2])

In [3]:
e.ndim

1

In [6]:
r = np.array(6)
print("R:",r)
print("DIM:", r.ndim)

R: 6
DIM: 0

In [7]:
y = np.array([[3,7,1], [9,2,4]])
print("Y:",y)
print("DIM:", y.ndim)

Y: [[3 7 1]
 [9 2 4]]
DIM: 2

In [11]:
e = np.array([5,1,7,9,2])
print("E:",e)
print("0 INDEX:",e[0])
print("4 INDEX:",e[4])

E: [5 1 7 9 2]
0 INDEX: 5
4 INDEX: 2

In [12]:
y = np.array([[3,7,1], [9,2,4]])
print("Y:",y)
print("DIM:", y.ndim)

Y: [[3 7 1]
 [9 2 4]]
DIM: 2

In [13]:
y[0]

array([3, 7, 1])

In [15]:
y[0][2]

np.int64(1)

In [16]:
y[1]

array([9, 2, 4])

In [17]:
y[1][2]

np.int64(4)

In [22]:
y[0:2 , 1:]

array([[7, 1],
       [2, 4]])

In [24]:
print("DIMENSION:",y.ndim)
print("Type Y:" , type(y))
print("DTYPE:" , y.dtype)

DIMENSION: 2
Type Y: <class 'numpy.ndarray'>
DTYPE: int64

In [25]:
print(y.astype("float"))

[[3. 7. 1.]
 [9. 2. 4.]]

In [26]:
print(y.astype("str"))

[['3' '7' '1']
 ['9' '2' '4']]

In [27]:
m = 7
print(m)
print(type(m))
print()
e = float(m)
print(e)
print(type(e))

7
<class 'int'>

7.0
<class 'float'>

In [29]:
dss = pd.read_csv("/content/Retail_Dataset_Modified.csv")
dss

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [30]:
type(dss)

pandas.core.frame.DataFrame

In [31]:
dss.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [34]:
dss["Store_Name"]

0          BrandX_India Superstore Pune
1        BrandX_India Superstore Mumbai
2              BrandX_India Trends Pune
3           BrandX_India Trends Chennai
4          BrandX_India Connect Chennai
                     ...
5166          BrandX_India Style Jaipur
5167          BrandX_India Daily Mumbai
5168    BrandX_India Gadget Zone Kanpur
5169          BrandX_India Style Mumbai
5170     BrandX_India Electronics Delhi
Name: Store_Name, Length: 5171, dtype: object

In [35]:
type(dss["Store_Name"])

pandas.core.series.Series

In [36]:
dss.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [37]:
dss[['Store_Name', 'Brand_Name']]

                           Store_Name    Brand_Name
0        BrandX_India Superstore Pune  BrandX_India
1      BrandX_India Superstore Mumbai  BrandX_India
2            BrandX_India Trends Pune  BrandX_India
3         BrandX_India Trends Chennai  BrandX_India
4        BrandX_India Connect Chennai  BrandX_India
...                               ...           ...
5166        BrandX_India Style Jaipur  BrandX_India
5167        BrandX_India Daily Mumbai  BrandX_India
5168  BrandX_India Gadget Zone Kanpur  BrandX_India
5169        BrandX_India Style Mumbai  BrandX_India
5170   BrandX_India Electronics Delhi  BrandX_India

[5171 rows x 2 columns]

In [38]:
type(dss[['Store_Name', 'Brand_Name']])

pandas.core.frame.DataFrame

In [43]:
dss["Store_Name"][0].upper()   # INDEXING+STRING METHOD

'BRANDX_INDIA SUPERSTORE PUNE'

In [60]:
len(dss["Store_Name"][0])

28

In [44]:
dss

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [46]:
dss.head(9)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
5,BX_DELHI_082,BrandX_India Superstore Delhi,BrandX_India,Street Store,Delhi,Metro,Toor Dal 1kg,Groceries,Dal,New Launch,...,81.3,85.3,Aggressive,Low,4.0,108,1,2022,Q1,Spring
6,BX_MUMBAI_062,BrandX_India Accessories Mumbai,BrandX_India,Street Store,Mumbai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Mature,...,98.0,81.6,Competitive,Low,2.0,90,1,2022,Q1,Spring
7,BX_DELHI_062,BrandX_India Digital Delhi,BrandX_India,Mall Store,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Mature,...,81.6,82.4,Competitive,Low,3.0,137,1,2022,Q1,Spring
8,BX_MUMBAI_042,BrandX_India Appliances Mumbai,BrandX_India,Street Store,Mumbai,Metro,NaN,Home Appliances,Water Purifiers,Declining,...,96.3,82.7,Aggressive,Low,4.0,214,1,2022,Q1,Spring

In [47]:
dss.tail(9)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5162,BX_MUMBAI_067,BrandX_India Mobile Mumbai,BrandX_India,Street Store,Mumbai,Metro,Sony Alpha a7 IV,Gadgets,Cameras,Growing,...,98.1,80.1,Aggressive,Low,6.0,146,11,2022,Q4,Winter
5163,BX_KANPUR_030,BrandX_India Digital Kanpur,BrandX_India,Mall Store,KANPUR,Tier2,iPhone 14,Electronics,Smartphones,Discontinued,...,76.6,63.8,Standard,Low,2.0,242,10,2022,Q4,Winter
5164,BX_MUMBAI_020,BrandX_India Gadget Zone Mumbai,BrandX_India,Street Store,Mumbai,Metro,LG OLED 55Inch,Electronics,Smart TVs,Declining,...,79.6,88.4,Competitive,Low,1.0,101,8,2024,Q3,Monsoon
5165,BX_CHENNAI_047,BrandX_India Fresh Chennai,BrandX_India,Online Hub,Chennai,Metro,Moong Dal 1kg,Groceries,Dal,Mature,...,79.7,89.8,Aggressive,Low,2.0,99,1,2024,Q1,Spring
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [49]:
dss["Store_Name"][0:6]

0      BrandX_India Superstore Pune
1    BrandX_India Superstore Mumbai
2          BrandX_India Trends Pune
3       BrandX_India Trends Chennai
4      BrandX_India Connect Chennai
5     BrandX_India Superstore Delhi
Name: Store_Name, dtype: object

In [50]:
for t in dss["Store_Name"][0:6]:
  print(t)

BrandX_India Superstore Pune
BrandX_India Superstore Mumbai
BrandX_India Trends Pune
BrandX_India Trends Chennai
BrandX_India Connect Chennai
BrandX_India Superstore Delhi

In [51]:
for t in dss["Store_Name"][0:6]:
  print(t.upper())

BRANDX_INDIA SUPERSTORE PUNE
BRANDX_INDIA SUPERSTORE MUMBAI
BRANDX_INDIA TRENDS PUNE
BRANDX_INDIA TRENDS CHENNAI
BRANDX_INDIA CONNECT CHENNAI
BRANDX_INDIA SUPERSTORE DELHI

In [52]:
g = dss.select_dtypes(exclude="object")
g

,Unit_Price,Cost_Price,Profit_Margin,Average_Order_Value,Inventory_Turnover,Days_of_Stock,Promotion_Impact,Max_Discount_Offered,Return_Rate,Customer_Satisfaction,...,Review_Count,Sales_Rep_Experience,Sales_Rep_Rating,Market_Share,Competitor_Count,Brand_Loyalty,Brand_Awareness,Delivery_Time,Month,Year
0,305,239,21.64,432,2.30,156,23.1,9,3.1,4.0,...,53,5,4.8,15.3,8,70.8,75.7,6.0,1,2022
1,47,33,29.79,63,3.11,116,34.9,21,2.9,3.9,...,202,10,3.6,18.9,25,80.5,81.5,4.0,1,2022
2,2140,1715,19.86,2994,1.73,208,29.4,36,6.3,4.3,...,77,1,4.0,14.2,11,68.5,76.7,4.0,1,2022
3,3534,2894,18.11,4416,1.62,222,37.3,31,4.0,4.4,...,221,7,3.9,16.4,19,92.4,88.0,5.0,1,2022
4,50676,40467,20.15,54629,2.80,128,33.1,43,4.8,3.9,...,205,6,4.9,13.4,19,82.9,89.5,2.0,1,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,2373,1972,16.90,2617,0.45,797,37.9,48,7.9,4.2,...,368,6,4.9,10.9,7,91.3,68.7,3.0,11,2024
5167,54,43,20.37,58,3.85,93,34.5,13,5.0,3.7,...,424,3,4.8,14.1,21,81.6,82.0,7.0,7,2023
5168,75554,52990,29.86,94881,1.77,203,0.0,0,5.3,3.9,...,326,6,3.8,11.3,6,89.9,68.1,1.0,7,2023
5169,11102,9267,16.53,16105,1.61,224,29.1,30,4.0,4.4,...,73,1,3.6,12.5,17,80.6,86.5,3.0,12,2022
5170,117390,82950,29.34,166575,0.75,480,0.0,0,6.9,4.7,...,500,1,4.4,27.2,18,91.8,85.0,3.0,6,2024

In [53]:
g2 = dss.select_dtypes(exclude="object").columns
g2

Index(['Unit_Price', 'Cost_Price', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Promotion_Impact',
       'Max_Discount_Offered', 'Return_Rate', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competitor_Count', 'Brand_Loyalty',
       'Brand_Awareness', 'Delivery_Time', 'Month', 'Year'],
      dtype='object')

In [55]:
g["Unit_Price"]

0          305
1           47
2         2140
3         3534
4        50676
         ...
5166      2373
5167        54
5168     75554
5169     11102
5170    117390
Name: Unit_Price, Length: 5171, dtype: int64

In [56]:
g["Unit_Price"][:10]

0       305
1        47
2      2140
3      3534
4     50676
5       173
6     51299
7    103410
8     17070
9       808
Name: Unit_Price, dtype: int64

In [57]:
g["Unit_Price"][:10].sum()

np.int64(229462)

In [59]:
max(g["Unit_Price"][:10])

103410